name: Crear enunciados 

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/enunciado.pdf enunciado.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
