name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create output directory
        id: create_output
        run: mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/enunciado.pdf enunciado.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
